name: kv
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  marquee: ^2.1.0
  chewie:
  responsive_builder: ^0.4.1
  firebase_storage:
  flutter_icons: ^1.1.0
  eva_icons_flutter:
  camera: ^0.8.1
  font_awesome_flutter: ^9.0.0
  firebase_auth:
  timeago: ^3.0.2
  cloud_firestore:
  page_transition: "^1.1.7+6"
  cached_network_image:
  provider:
  animations:
  animator:
  get_it:
  http:
  async:
  video_thumbnail: ^0.3.3
  intl:
  uuid:
  image_picker:
  video_player:
  # flick_video_player: ^0.3.1
  file_picker: ^3.0.1
  path_provider:
  google_fonts:
  image_cropper:
  flutter_image_compress:
  firebase_core:
  google_sign_in:
  custom_navigation_bar:
  video_compress:
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/3164.jpg
